### PR TITLE
Roster implementation

### PR DESCRIPTION
**Pull request by LogansUA**
@Myrkotyn you should also watch on this!

### CODE REVIEW

**Comment by LogansUA** [comment]
PR-s are welcom :smile:

**Comment by Myrkotyn** [comment]
ROFL

**Comment by LogansUA** [comment]
@Myrkotyn ?

**Comment by Myrkotyn** [comment]
you have awesome commits =)

2016-07-28 13:18 GMT+02:00 Oleg Kachinsky <notifications@github.com>:

**Comment by LogansUA** [comment]
@Myrkotyn Yeah, but i failed with "Translliterize names to" it was miss-click, should be "Transliterize names to Latin".

**Pull request merged**
